UKHomeOffice/hocs-casework

src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/StageRepository.java, src/main/resources/db/migration/postgresql/V1_1__CREATE_CASE_STAGE.sql, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java
Because our business logic doesn't allow a user to own a case outside of their team, selecting just the teams will return all the users cases too, its still up to the frontend to filter these cases as it wants.
=> Simpler workstack query

src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/Stage.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/StageRepository.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/domain/model/StageTest.java
The basis of stage searches and selects on the database was the fact that only the latest stage contained the team information. The meant that all the stages, except the latest, were void of team and user information and audit had to be relied upon to provide that.
Now that the team and user information is being updated correctly, the searches and selects had to be modified to return only the last stage. This is done with timestamp or by using the void user field for multiple case selects.
Although the design is to return multiple stages on the rest calls, the front end never had to process them and is not in a state to do so after trying to send multiples. The server endpoints therefore only return the latest for both search and reference find capabilities.
=> Hocs 1035 stage user and team

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResource.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataCreateCaseIntegrationTest.java
Allow task force to upload docs; creating claim requires "owner" access level. Merge to WCS.
=> HOCS-1360 : task force team upload docs

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentService.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/documentclient/GetDocumentsResponse.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/client/documentclient/DocumentClientTest.java
Enrich endpoint that retrieves list of documents for a case with additional list of document tags for the case type.
=> HOCS-1551 : make document tags case type specific, fix

src/main/resources/application-local.properties
This should reduce the number of redundant calls this service
makes when we don't have docs or audit running locally.
This significantly improves the response time on local env.
=> Updating local retry config

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseworkConstants.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java
- blanking CurrentStage value when case is withdrawn
- blanking CurrentStage value when case is completed
- case updated audit had to be triggered on case completion for
the case_data extract to pick up field changes.
=> HOCS-1910 - CurrentStage value should when a case is completed

src/main/resources/db/migration/postgresql/V1_6__2195_Multiple_Contributions_Add_Somu_Item.sql
Add the single use multi use item table that will be used with Multiple Contributions to store lists. This also includes the constraints and indexes required.
=> HOCS-2195: add Single Object Multi Use table

src/main/resources/db/migration/postgresql/V1_7__2195_Multiple_Contributions_Somu_Item_Correct_Index.sql
When creating the somu_item table an incorrect index was created 'idx_somu_item_uuid' that pointed to somu_item(case_uuid). This should have been pointing to somu_item(uuid).
There is also a redundant index in 'idx_somu_item_case_uuid' as a result of 'idx_somu_item_case_uuid_type'. This is because indexes work left to right in subsets. so this indexes case_uuid and case_uuid and type together.
=> HOCS-2195: Correct indexes on somu item table

.drone.yml
Drone 1.0 does a good job of emulating various Bash string operations,
but this doesn't seem to be supported in Drone 0.8. This commit changes
the behaviour to a hacky workaround with sed, which should do the job.
When we migrate to Drone 1.0 we can tidy this up again by reverting this
commit.
=> HOCS-2240 Use sed instead of variable substitution

.drone.yml
Drone requires that interpolated variables have a double dollar sign.
I'm not sure why.
=> HOCS-2240 Add missing dollar sign

src/main/java/uk/gov/digital/ho/hocs/casework/api/SomuItemService.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/SomuItemServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/dto/GetSomuItemResponseTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/domain/model/SomuItemTest.java
At present when we try and get a somu item, if the item is not found then we currently throw an entity is not found exception. Whereas the new functionality means that a dummy somu item is created (that's classed as deleted) that will allow for the frontend to add and populate data based on the somu item uuid.
=> HOCS-2235: change somu item to upsert on no retrieval

src/main/java/uk/gov/digital/ho/hocs/casework/api/SomuItemResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/CreateSomuItemRequest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/SomuItemResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/dto/CreateSomuItemRequestTest.java
Change the upsert of a somu item to expect CreateSomuItemRequest object (which is just a data json string). This allows us to get past the funky encoding that the frontend does with form encoding if we send a string as the body.
=> HOCS-2236: upsert somu item improvements

src/main/java/uk/gov/digital/ho/hocs/casework/client/infoclient/EntityTotalDto.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/DataTotal.java, src/test/java/uk/gov/digital/ho/hocs/casework/domain/model/DataTotalTest.java
HOCS-2254 adds additional uplift amounts.
These values need to be totalled up in Total Awarded and Total Paid.
Currently these totals are made of lists of fields to add and fields to subtract. Each field has a corresponding "check field", the value of which is used to determine whether to include the field in the total. As this check field is also used as the key to the map of fields to add, it is currently impossible to add two value fields with the same check field.
This change allows an array to be passed with each check field, whilst still accepting single values. I chose this solution as it allows existing projects to remain unaffected.
=> HOCS-2254-Allow multiple value fields for each check field

src/main/java/uk/gov/digital/ho/hocs/casework/client/auditclient/AuditClient.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/auditclient/dto/AuditPayload.java, src/test/java/uk/gov/digital/ho/hocs/casework/client/auditclient/AuditClientTest.java
At present we are currently trying to map a string to JSON, which results in invalid JSON being received by the audit service. This change encompasses this by having a basic SomuItem class that contains just the SomuTypeUUID for the View. This class is inherited when we do a update, add or delete of an SomuItem to allow for further information being passed.
=> HOCS-2199: Change to audit payloads

src/main/java/uk/gov/digital/ho/hocs/casework/api/StageResource.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageResourceTest.java
The case-creator service needs a way to find out the current active stage for a case.
This endpoint was added to allow that query.
It does return a Set but I believe that there can only be one active stage for a case. (I think the Set is a JPA limitation)
The client side code checks the Set length and if there is more than one it will raise an exception.
=> HOCS-2555 - New endpoint to return active stage for a given case.

.drone.yml
This change implements the necessary changes to use Drone V1 as V0.8
is going to be deprecated. Changes include:
- Split build and deploy into two pipelines
- Removed pull request checks
- Changed to push to build_XXX instead of build-XXX
- Added commit sha tag
- Switched to using KUBE_TOKEN as defined in Drone rather than the kube 
repo
- Added acyclic dependency graph for asynchronous build steps
- Made a QA release always release to both QA environments
consolidated build steps where possible
=> HOCS-2640: migrate from drone 0.8 to 1

src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/SearchRequest.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/searchclient/SearchClient.java
The frontend calls to this service and then casework requests to search, 
therefore to allow for search to use the value it needs to be passed
through
=> HOCS-2680: push through `poTeamUuid`

bin/.gitignore, build.gradle, src/main/java/uk/gov/digital/ho/hocs/casework/application/SpringConfiguration.java, src/main/java/uk/gov/digital/ho/hocs/casework/application/SwaggerConfiguration.java
This ticket adds a Swagger service to casework giving us access to all the exposed api endpoints published by the casework service.
The Swagger page is available at http://localhost:8082/swagger-ui.html
=> HOCS-2457 add Spring config to allow Swagger service on casework

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResource.java
Currently if we want to update case data, the case has to be 
allocated to the user. As we now allow for WCS cases to be moved 
without allocation. This needs to be changed to accommodate the 
CaseworkTeamUUID data update. To still have some protection, this 
change makes it so the user has to be part of a team that allows 
WRITE permissions.
=> HOCS-2975: change endpoint protection

scripts/CsvCaseDataUpdater.java
At present to update cases within the system we have to manually 
create the url requests to be able to update the data or change the 
live data through the frontend. This is easily error prone and 
requires a lot of time to achieve. To improve this mechanism this 
change adds a scripts that takes an absolute csv filepath and 
updates the data based on whats passed in. A new dry run option 
has been added whereby an `update` (case insensitive) second arg 
should be provided to actually send the requests. To make it clear 
what each of the updates are going to do, the script also logs each 
request and the value that it is updating. If the request is successful 
we now also log that. 
As the script is embedded within the `hocs-casework` image, we 
can call the service directly through …
=> HOCS-2822: add csv case data updater script

src/main/resources/application.properties
During a Live Service incident we saw that there was occurences
whereby the default connection pool size of 10 were all being used
up. This was causing the pods to crash and fail the health check.
To remediate from this, the default connection pool size has been
increased to 20 while we investigate what the correct number for
the system should be.
=> HOCS-3421: increase hikari connection pool size

.drone.yml
This adds a step to Drone that fires on push to the FOI epic branch,
which triggers a deployment to the hocs-gamma environment.
Previously we were deploying manually to hocs-gamma, and using a fixed
branch-based tag, which was causing inconsistencies and confusion. Here
we deploy a tag based on the Drone build number, which is easier to
track. If we wanted, we could deploy using the SHA hash for a similar
effect.
=> HOCS-2885 Push FOI MVP to hocs-gamma automatically

.drone.yml
It appears that one of the two `build and push` commands that we have
routinely fails. To try and simplify this and remove this edge case, we
now only run one on a push to branches and one on push to main.
=> Simplify Drone Pipeline

src/main/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/CorrespondentTypeDto.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCorrespondentWithPrimaryFlagResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/utils/CorrespondentTypeNameDecorator.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoClient.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/BaseCorrespondent.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/Correspondent.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CorrespondentWithPrimaryFlag.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/DeleteCorrespondentIntegrationTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/GetCorrespondentIntegrationTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/GetCorrespondentsIntegrationTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/MigrationCorrespondentServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/UpdateCorrespondentIntegrationTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCorrespondentTypeResponseTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCorrespondentsResponseTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/utils/CorrespondentTypeNameDecoratorTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoClientTest.java
Add a decorator that will take a list of CorrespondentTypeDto and
Correspondents and populate the `typeDisplayName`field of the
Correspondent if the value is there.
This new decorator is then called within the CorrespondentService
when returning Correspondents.
=> HOCS-3645: add correspondent type display name

src/main/java/uk/gov/digital/ho/hocs/casework/api/StageResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/StageRepository.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java
Add an endpoint that returns all the active stages that the user
should have access too. This endpoint calls a native query that first
gets the stages that the user is assigned too, and then cross-references
with the teams the user has access to. As we have access to the
case data at this stage, this change also filters on `Unworkable`.
On QAX when timing the current `\stage` endpoint vs this new one with 
50 users hitting the system at the same time, the response time by the
service was as follows:
`Class: uk.gov.digital.ho.hocs.casework.api.StageResource. Method: getActiveStages. Execution time: 9405ms`
`Class: uk.gov.digital.ho.hocs.casework.api.StageResource. Method: getActiveStagesForUser. Execution time: 88ms`
=> HOC-3670: stage user endpoint

scripts/CsvCaseDataUpdater.java
Currently, when we get a non-200 code from a request the rest of the
urls don't get requested. This can lead to partial updates which aren't
ideal. This change logs out a severe error when this occurs instead of
terminating the program.
=> HOCS-3787: Change failed response handling for CSVCaseDataUpdater

src/main/java/uk/gov/digital/ho/hocs/casework/contributions/ContributionsProcessorImpl.java, src/test/java/uk/gov/digital/ho/hocs/casework/contributions/ContributionsProcessorTest.java
This change passes through the highest contribution status for a MPAM
case. This allows us to be able to differentiate between a case that is
received (and thus there is no due contribution) and those cases that
don't have any.
=> HOCS-3848: pass-through contribution status

src/main/java/uk/gov/digital/ho/hocs/casework/contributions/ContributionSomuInspector.java, src/test/java/uk/gov/digital/ho/hocs/casework/contributions/ContributionsDateProcessingTest.java
Adds a datetimeformatter to let LocalDate.parse() handle leading zeros and also a lack of zeros.
=> HOCS-3852 Make contribution processing handle leading zeros

src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyCompToComp2.java
Three fields were missing when escalating a complaints case from stage 1 to stage 2. This adds the three fields to the copy class.
=> HOCS-3831: Fix missing Stage 2 Case Data

.drone.yml
Drone seems to break if you run `docker push` more than once
simultaneously. This commit neatens things up so that only one push step
is run for any given pipeline.
=> Stop Drone running two Docker push steps

src/main/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/CreateCorrespondentRequest.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCorrespondentResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCorrespondentWithPrimaryFlagResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/UpdateCorrespondentRequest.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/BaseCorrespondent.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/Correspondent.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CorrespondentWithPrimaryFlag.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/MigrationCorrespondentResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/MigrationCorrespondentService.java, src/main/resources/db/migration/postgresql/V1_20__3730-Add-Organisation-Field.sql, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/MigrationCorrespondentServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCorrespondentOutlineResponseTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCorrespondentOutlinesResponseTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCorrespondentResponseTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCorrespondentWithPrimaryFlagResponseTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCorrespondentsResponseTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyCompToComp2Test.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/utils/CorrespondentTypeNameDecoratorTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/client/auditclient/AuditClientTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/domain/model/CorrespondentTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/domain/model/CorrespondentWithPrimaryFlagTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/domain/repository/CorrespondentRepositoryTest.java
Adds an Organisation field used in FOI requests, this field is stored in the Correspondent table.
=> HOCS-3730 add organisation field to correspondent

src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/Stage.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/StageRepository.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/domain/repository/StageRepositoryTest.java
When trying to get the team uuid currently this queries the `stage_data`
view that returns not only more information than required but also
computes every join. As the required data is immediately
available on the `stage` table, this can easily be retrieved through a
projection, saving the computation time of the view.
During testing on QA with around 70k current stages, the old query returned
in 60ms (without load) whilst the new one was around 1ms (without load).
=> HOCS-3858: get stage team through projection

src/main/java/uk/gov/digital/ho/hocs/casework/contributions/ContributionSomuInspector.java, src/main/java/uk/gov/digital/ho/hocs/casework/contributions/ContributionsProcessorImpl.java, src/main/java/uk/gov/digital/ho/hocs/casework/contributions/FOIContributionStages.java, src/test/java/uk/gov/digital/ho/hocs/casework/contributions/ContributionSomuInspectorTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/contributions/ContributionsProcessorTest.java
This change re-works adds in FoI contributions into the ContributionsProcessor so that it is returned neatly as part of the stage object. 
As a result of there being a SOMU Type that is not a contributions a filtering has been applied to remove the non-contributions.
=> HOCS-3848: return FoI contributions

src/main/java/uk/gov/digital/ho/hocs/casework/api/SomuItemResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/SomuItemService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/auditclient/AuditClient.java, src/main/java/uk/gov/digital/ho/hocs/casework/contributions/ContributionsProcessor.java, src/main/java/uk/gov/digital/ho/hocs/casework/contributions/ContributionsProcessorImpl.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/SomuItemRepository.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/SomuItemResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/SomuItemServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/contributions/ContributionsProcessorTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/domain/repository/SomuItemRepositoryTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/domain/repository/StageRepositoryTest.java, src/test/resources/stage/afterTest.sql
Presently, when a workstack is loaded, a call is made for each 'stage'
is part of that workstack to retrieve the contributions. This is causing
potentially thousands of calls and taking more resources than necessary
This change requests all the contributions for all the stages at once,
leading to only one hit on the database.
A side effect of this is we can revert the auditing code that was
applied previously.
=> HOCS-3979: contribution processor improvements

Dockerfile, scripts/run.sh
This commit moves us to a multi-stage docker build with a layered jar instead of a fat jar. The objective is to reduce the springboot startup time in k8s environments, a side effect is more efficent docker layer caching for developer flow.
This change in isolation reduces the Startup time in k8s from 
Started HocsCaseApplication in 24.14 seconds (JVM running for 25.76)
to
Started HocsCaseApplication in 10.893 seconds (JVM running for 11.479)
=> HOCS-4073: use multi-stage docker file

src/main/java/uk/gov/digital/ho/hocs/casework/api/SomuItemService.java
Currently, we are printing out all the case uuids that we are
requesting the somu items for in the SomuItemService. This is causing
extremely long logs in production that get split over multiple lines
every time a call to the callee happens. This is a change to the log
line to print out the number of cases that and somu items that have been
retreived as printing potentially thousands of uuids isn't particulary
useful.
=> HOCS-4045: update log line

src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/BaseStage.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/StageWithCaseData.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/domain/model/StageWithCaseDataTest.java
This commit gets 'updateStageCurrentTransitionNote' to use the simpler (quicker) repository method without the topics/correspondents/case data, and moves some methods that can go on the base object 'baseStage' from the stage subtypes to enable this.
=> Hocs-4235 -'updateStageCurrentTransitionNote' is using a slow query

src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java
This commit gets 'recreateStage' to use the simpler (quicker) repository method without the topics/correspondents/case data.
=> Hocs-4235 -'recreateStage' is using a slow query

src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java
This commit moves 'getTeams' to use the existing getBasicStage method, this isn't an important change on its own but it is the first part of being able to return a 'Stage' object in callers to the Casework service instead of calling it n times in one method for specific fields as we do now.
It also puts back an exception where there stageUUID is not found in the database - this is different to 'inactive' stages which don't have teams assigned to them
=> Hocs-4235 -'getTeams' should use the existing getBasicStage method

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/StageResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/CreateStageResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/BaseStage.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/StageWithCaseData.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java
This commit
1) Gets 'createStage' to use the simpler (quicker) repository method without the topics/correspondents/case data.
2) Puts the database code in a transaction as we're modifying two tables
3) Removes multiple calls to getCaseData when one will do.
=> Hocs-4235 -'createStage' is using a slow query

src/main/java/uk/gov/digital/ho/hocs/casework/api/ActionDataAppealsService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/ActionDataExternalInterestService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/auditclient/AuditClient.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/auditclient/dto/AuditPayload.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/ActionDataAppealsServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/ActionDataExternalInterestServiceTest.java
* Stop saving case notes for actions
* Rely on the audit timeline for action notes
=> HOCS-4198 Extra blank case note when adding/updating appeals and 'System Event' log in timeline when an extension is applied

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/CaseDataRepository.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/domain/repository/StageRepositoryTest.java
'getRef' is always called when we have access to the reference already
This commit removes 'getCaseRef' as every time it is called we already have access to the case reference and we don't need to fetch it again from the case_data table.
=> Hocs-4235 -'getRef' is always called when we have access to the reference already

.github/dependabot.yml
Update to the dependabot configuration to ignore the patch versions for
the aws java library used. This library is used every day as a BOM with
all services. This leads to dependabot changes daily that aren't
required. We ignore the patch versions (excluding security issues) to
reduce this overhead.
=> Dependabot: ignore aws-java-sdk-sns patch

src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java
This change adds the Withdrawal Reason to the case data blob to allow
the propagation into MI reports.
=> HOCS-4477: add withdrawal reason to case_data 

src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBfToBf2.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBfToBf2Test.java
Removes case summary, previous complaint reference, third party reference
from field auto population on BF2 case creation
=> HOCS-4716 BF2 Field auto population fix

build.gradle, src/main/resources/application.properties
The latest 2.15.1 version of the `hibernate-types` requires the 'Range'
class of Guava (which it does not provide). As we have Guava in our test
dependencies this change passes current tests. Changing this to a
general `implementation` gives runtime access to the library.
We use `hibernate-types-52` which is suitable for Hibernate
`5.4, 5.3, 5.2`. The hibernate library is currently 5.6.7 which doesn't
have a hibernate-types library. This change upgrades to the closest
match for the time being.
=> Fix dependancy issues

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/auditclient/AuditClient.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataServiceTest.java
HOCS-4980: pass the created date to allow audit service not to search table partitions for audit events before the case was created.
=> HOCS-4980: pass the created date to timeline lookup

src/main/java/uk/gov/digital/ho/hocs/casework/priority/StagePriorityCalculatorImpl.java, src/main/java/uk/gov/digital/ho/hocs/casework/priority/policy/StagePriorityPolicy.java, src/main/java/uk/gov/digital/ho/hocs/casework/priority/policy/WorkingDaysElapsedPolicy.java, src/test/java/uk/gov/digital/ho/hocs/casework/priority/StagePriorityCalculatorImplTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/priority/policy/WorkingDaysElapsedPolicyTest.java
Previously there was a necessary case type marker that was added to the
case data blob during priority calculation that allowed for exemption
dates to be returned. As the whole StageWithCaseData object is passed
now, the case type is available in the resultant call. Therefore, this
marker is no longer required and has been removed.
=> HOCS-5354: remove CASE_TYPE_MARKER

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCaseConfigResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCaseTypeResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoClient.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CaseConfig.java
This changes sets up the ability to remove the serving of case type tabs from hocs-info-service. This is supported through a new enpoint that is used by the frontend to designate the tabs to show from a configuration file. 
As a result the case configuration endpoint and surrounding implementations have been flagged as deprecated for future removal.
=> HOCS-5363: serve tabs from frontend

src/main/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentService.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CorrespondentWithPrimaryFlag.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentServiceTest.java
A previous change caused the correspondent type name to not return with
the `getCorrespondents` method. This change ensures the type name is
appended with the correspondents.
=> HOCS-5465: add correspondent type name

src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCaseSummaryResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/AdditionalField.java
Add Equals and HashCode method to AdditionalField to allow for Sets to
strip duplicates as by default these use the internal memory address
of the object.
=> HOCS-5462: add equals and hash code

src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyPOGRtoPOGR2.java
Add missing `ComplaintNationOrigin` key to copy from POGR cases when
escalating to POGR2.
=> HOCS-5521: add missing POGR->POGR2 key

src/main/resources/config/priority-policies.json
Add the POGR2 priority policy configuration. This is the same as the
POGR configuration.
=> HOCS-5575: add POGR2 priority policy

src/main/resources/config/details/stages/IEDET.json
Fix the FinalResponseDocument field to ensure that the correct choice is
used to convert the uuid to the name of the document.
=> HOCS-5629: fix choices for accordion field

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseProfileResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoClient.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CaseTypeDocumentTags.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/CaseTypeDocumentTagRepository.java, src/main/resources/config/document-tags/BF.json, src/main/resources/config/document-tags/BF2.json, src/main/resources/config/document-tags/COMP.json, src/main/resources/config/document-tags/COMP2.json, src/main/resources/config/document-tags/DTEN.json, src/main/resources/config/document-tags/FOI.json, src/main/resources/config/document-tags/IEDET.json, src/main/resources/config/document-tags/MIN.json, src/main/resources/config/document-tags/MPAM.json, src/main/resources/config/document-tags/MTS.json, src/main/resources/config/document-tags/POGR.json, src/main/resources/config/document-tags/POGR2.json, src/main/resources/config/document-tags/SMC.json, src/main/resources/config/document-tags/TO.json, src/main/resources/config/document-tags/TRO.json, src/main/resources/config/document-tags/WCS.json, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoClientTest.java, src/test/resources/config/document-tags/TEST.json
Add the document tag information for all the case types on the system as configuration files.
Add a new document tag repository that replaces the existing `hocs-info-service` call to retrieve the document tags for a specific case type.
=> HOCS-5679: refactor document tags 

src/main/resources/config/document-tags/POGR.json, src/main/resources/config/document-tags/POGR2.json
1. This bug was related to PR - https://github.com/UKHomeOffice/hocs-casework/pull/753/files where all hocs-data changes been migrated to hocs-casework. 
2. Previously my changes were part of hocs-data (PR- https://github.com/UKHomeOffice/hocs-data/pull/1295/files) were not migrated to hocs-casework PR hence this bug has been raised.
3. My fix to POGR and POGR2 json will add back Contribution Request and Contribution Response to document types for these 2 case types.
=> Json changes to add new document types to POGR and POGR2 cases

src/main/resources/config/document-tags/IEDET.json
Add the `DRAFT` document tag to the IEDET list.
=> HOCS-5691: add DRAFT document tag

src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBfToBf2.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyCompToComp2.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyPOGRtoPOGR2.java, src/main/resources/config/details/stages/POGR2.json, src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBfToBf2Test.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyCompToComp2Test.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyPOGRToPOGR2Test.java
This bug is happening because before the correspondents are confirmed during the workflow there is no value for the primary correspondent in the case data blob
=> HOCS-5711: Copy correspondents field value

src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/CaseDataDetailsGroupsRepository.java
One case type is currently within the case details groups, this is then causing log events at warn level as all other case types are in the stages configuration. As this is expected behaviour - this change lowers the log level to info from this repository.
=> Lower log level for Case Details Groups

src/main/resources/config/details/stages/IEDET.json
Previously dev has changed hocs-workflow when the
user creates the correspondent and while 
displaying hocs-casework comes into play where 
the change was missed. 
This PR will help to fix the text changes in HOCS-5646.
=> HOCS-5847 - Updated IEDET json to fix the text

src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseService.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationStageService.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/dto/ComplaintCorrespondent.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/dto/CorrespondentType.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/dto/CreateMigrationCaseRequest.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/dto/MigrationComplaintCorrespondent.java, src/main/resources/config/details/stages/IEDET.json, src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseDataServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseServiceTest.java
Create Primary Correspondent and set as the primary correspondent for a case.
Primary Correspondent is saved as a correspondent in the database, then set as the primary correspondent for the migrated case.
=> Hocs 5583 - create correspondent for migrated case

src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/StageWithCaseData.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/CaseTagRepository.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java
There are currently performance issues with the tagging functionality whereby the use of native queries and JPA hibernate is causing queries per stage for tags.
While this functionality is being rewritten, this change falls back to using a 'somu'-esque loading mechanism to only query all stage tags at first.
=> HOCS-5920: rework tagging functionality

src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseService.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/dto/CreateMigrationCaseRequest.java, src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseDataServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseServiceTest.java
Adds ability to create additional correspondents (optional) from a migration request.
=> HOCS-5714 Create additional correspondents for migrated case

src/main/resources/config/details/stages/COMP.json, src/main/resources/config/summary/COMP.json
HOCS-6170-UI fixes for UKVI input fields. This PR would help to 
fix the bugs or concerns raised by QA team.
=> HOCS-6170-UI fixes for UKVI input fields

src/main/resources/config/details/stages/COMP.json, src/main/resources/config/details/stages/COMP2.json, src/main/resources/config/details/stages/SMC.json, src/main/resources/config/summary/COMP.json
Changed field labels in accordion and summary to use sentence case for COMP Registration and QA input stages and SMC Registration
Should match up with corresponding changes on hocs-workflow (https://github.com/UKHomeOffice/hocs-workflow/pull/921)
=> HOCS-6170: UKVI and SMC content updates for registration and QA input

src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyCompToComp2.java
Add the `BusAreaBasedOnDirectorate` option to the COMP->COMP2 case copy strategy.
=> HOCS-5122: add variable to copy strategy

src/main/java/uk/gov/digital/ho/hocs/casework/contributions/ContributionsProcessorImpl.java
Move processor logging to DEBUG, introduce new INFO log line. New INFO level log will only be logged once for the set, rather than once per iteration as with the now DEBUG level log lines.
=> HOCS-6196 Alter contribution processor logging

src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java
There was a regression in functionality with the implementation of FOI Dispatch. This resulted in DCU cases going through the same code path with an override being ignored. This causes issues with deadlines, and therefore business SLAs being met. This change corrects this code path so that FOI extensions do not impact overrides.
=> HOCS-6264: correct stage override date setting

src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseService.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/dto/CreateMigrationCaseAttachmentRequest.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/dto/CreateMigrationCaseRequest.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/dto/CreateMigrationCaseResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/dto/CreateMigrationCorrespondentRequest.java, src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseDataServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseServiceTest.java
Create 2 endpoints for:
- case creation (also creates respective stage).
- correspondent creation (primary and optional additional).
- case attachment creation removed. To be called directly from case-creator in this associated [PR](https://github.com/UKHomeOffice/hocs-case-creator/pull/237).
=> HOCS-6211: Create case correspondents attachments endpoints

src/main/java/uk/gov/digital/ho/hocs/casework/api/SomuItemService.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/auditclient/AuditClient.java
The audit line for retrieving all somu items for numerous cases is unnecessary. This would only be called when viewing the workflows.
=> HOCS-6497: remove somu items for case uuid audit

src/main/resources/config/summary/IEDET.json
Wording was `Response date`, this should have been `Response sent` to be clearer on the meaning.
=> HOCS-6189: fix summary wording

src/main/resources/config/details/stages/COMP.json
The previous change under HOCS-6548 erroneously changed a visibility condition, this has caused a field to no longer display to the user.
=> HOCS-6548: correct visibility condition

src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/AbstractCaseData.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CaseData.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseService.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/dto/CreateMigrationCaseRequest.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/client/auditclient/MigrationAuditClient.java, src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseDataServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseServiceTest.java
Updates the migration case creation so that it only completes the case and audits when a completed date is passed in.
This also corrects the timestamps used in audit to use the migrated case dates rather than Now.
=> [HOCS-6247] Changes to allow migrating open cases

src/main/java/uk/gov/digital/ho/hocs/casework/client/auditclient/dto/AuditPayload.java
HOCS-6476 : This PR will include audit_event changes to accommodate
migratedReference when the case is updated. This would 
help reports to capture the data for DECS users.
=> HOCS-6476: Add migratedReference to update case audit event

src/main/java/uk/gov/digital/ho/hocs/casework/api/StageResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java
Add the ability to specify whether the current team should be saved in another field when allocating. This only happens if the field name is specified and saveLast is true. If saveLast is false and the field is specified, the value is cleared.
=> HOCS-6597: add optional saving of last team on team update

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentService.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/documentclient/DocumentClient.java
Deprecation of document file download endpoints, as this is no longer handled through this service, but directly on the document service.
=> HOCS-6562: deprecate file download endpoint and methods

src/main/resources/db/migration/postgresql/R__6410_correspondents_json_by_case.sql, src/main/resources/db/migration/postgresql/R__6410_stage_data.sql
HOCS-6410: With https://github.com/UKHomeOffice/hocs-casework/pull/992 
PR, the container is not coming up so on review decided to remove alter 
statement which is causing the issue.
=> HOCS-6410: remvoe alter statement to run as root

src/main/resources/config/details/stages/COMP2.json
The bug is cause because the frontend doesn't have the directorate value to evaluate the conditional choices, this adds the directorate value to the accordion bringing it in line with COMP
=> HOCS-6802: Add directorate to COMP2 MM accordion

src/main/resources/config/details/stages/COMP2.json
'Is a Letter of Authority required?: Yes' text is now visible in Accordion for Minor misconduct UKVI stage 2
- Added missing JSON to Comp2.json (copied over from Comp.json.
=> HOCS-6821: Add accordion field

src/main/resources/config/document-tags/COMP.json
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-6861
- COMP.json edited to change the names of document tags as requested in the ticket.
- Order of appearance changed to adjust to new names.
=> [HOCS-6861]CCT-Rename-document-section-titles

src/main/resources/config/document-tags/COMP.json
Reverts UKHomeOffice/hocs-casework#1014
-Due to requiring confirmation of whether the changes should effect COMP/COMP2
=> Revert "[HOCS-6861]CCT-Rename-document-section-titles"

src/main/resources/config/document-tags/COMP.json, src/main/resources/config/document-tags/COMP2.json
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-6861
Updates:
- Document name changes added to COMP
***Addition - Document name changes added to COMP2***
=> Fix/hocs 6861/cct rename document section titles

src/main/resources/config/document-tags/COMP.json
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-6960
=> [HOCS-6960] Restore Migrated CMS document to COMP case types
