src/main/java/uk/gov/digital/ho/hocs/casework/casedetails/model/CaseType.java, src/main/java/uk/gov/digital/ho/hocs/casework/casedetails/model/StageType.java
c.f. UKHomeOffice/hocs-workflow#10
=> Add enums for BREF case type

src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/main/resources/logback-spring.xml
Add additional logging around workstacks
=> Fix logback MDC logger

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/infoclient/GetSummaryFieldsResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoClient.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataServiceTest.java
This code removes the info client stub and will get the correct fields to show in the summary for a given case type (subject to test data in info service)
=> integrate case summay fields

README.md, docker-compose.yml, src/main/java/uk/gov/digital/ho/hocs/casework/application/RequestData.java, src/test/java/uk/gov/digital/ho/hocs/casework/client/auditclient/AuditClientTest.java
- fix tests
- cleanup docker-compose
=> - Add readme

src/main/java/uk/gov/digital/ho/hocs/casework/api/TopicResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/TopicService.java, src/main/java/uk/gov/digital/ho/hocs/casework/application/LogEvent.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoClient.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/TopicResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/TopicServiceTest.java
Extra endpoint for the info service to call when a standard line is updated
=> HOCS-1204-flush-standard-line-cache added flush cache endpoint

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/CaseDataRepository.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java
(fixing the case reference not being populated when sending notify command)
=> HOCS-1312 - Nominated contact emails are failing to send

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCaseSummaryResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CaseSummary.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCaseSummaryResponseTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/client/auditclient/AuditClientTest.java
Update summary tab. Merge to WCS.
=> HOCS-1318 : update summary tab

src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetStageResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/Stage.java, src/main/resources/db/migration/postgresql/V1_3__UPDATE_STAGE_DATA_VIEW.sql
Add case created date for use in work stack.
=> HOCS-1439 : add case created date for use in work stack

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/infoclient/EntityTotalDto.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/DataTotal.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoClientTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/domain/model/DataTotalTest.java
New totals calculation to include subtraction functionality.
=> HOCS-1463 : Record an Urgent & Exceptional Payment (UEP)

src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCaseResponse.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCaseResponseTest.java
UUID replacement only replaces UUID strings
=> HOCS-1523 : UUID replacement only replaces UUID strings

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoClient.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataCreateCaseIntegrationTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java
Set different M-Ref deadline for whole Case lifetime, not per stage.
New endpoint to set deadline using different SLA (in days).
Calculation for Stage deadline includes Case deadline date for defaulting.
Merge to UKVI2.
=> HOCS-1581 : required by date for M-Ref cases

src/main/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/CorrespondentTypeDto.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCorrespondentTypeResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoClient.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/CaseDataRepository.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/MigrationCorrespondentServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCorrespondentTypeResponseTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoClientTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/domain/repository/CaseDataRepositoryIntTest.java
=> UKVI2 HOCS-1589 : add correspondent

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/UpdateTeamByStageAndTextsRequest.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/UpdateTeamByStageAndTextsResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoClient.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoClientTest.java
New endpoint to create the link value from the case data.
Merge to UKVI2.
=> UKVI2 HOCS-1582 : correspondence cases are sent to correct workstack

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoClient.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoClientTest.java
New endpoint to get document tags for given case, using case type.
=> HOCS-1551 : make document tags case type specific

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/UpdateStageDeadlineRequest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataServiceTest.java
New endpoint to update the stage deadline for given case to given number of days. Populates data map with override for new date.
=> HOCS-1799 : Home Secretary draft stage deadline

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java
Maintain order of mapped values.
=> HOCS-1820 : sort stage deadlines by progression, fix

src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java
adding missing unit tests for 'withdraw case' logic
=> HOCS-1816 - Withdraw a WCS claim

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentService.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/documentclient/DocumentDto.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/client/documentclient/DocumentClientTest.java
- added 'Primary Draft' label on primary draft document
=> HOCS-1825 - Primary Draft Tag in document list

src/main/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCorrespondentOutlineResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCorrespondentOutlinesResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/CorrespondentRepository.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCorrespondentOutlineResponseTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCorrespondentOutlinesResponseTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/domain/repository/CorrespondentRepositoryTest.java
New endpoint to return list of all correspondents UUIDs and fullnames.
=> HOCS-1914 : case data export convert uuid to text value

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCaseReferenceResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/CaseDataRepository.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResourceTest.java
Added a rest endpoint for case reference lookups with the uuid.
=> HOCS-1940-Allocations-Correspondents-MI

src/main/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentService.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/MigrationCorrespondentServiceTest.java
- added a logic so that when we add the first correspondent it is
automatically set as primary correspondent.
=> HOCS-1996 - UKVI - when a second correspondent

src/main/java/uk/gov/digital/ho/hocs/casework/client/auditclient/AuditClient.java
added missing values for deadline and deadline warning fields
=> HOCS-1963 added missing values for deadline and deadline warning fields

src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/SearchRequest.java
New text box to search for cases by full name of correspondents who are not MPs
=> HOCS-1997 : new text box to search for cases by fullname

.drone.yml
Fix accidental regression in previous commits.
Hopefully we'll squash these commits before they hit master.
=> HOCS-2240 Push image as well as just tag it

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/SomuItemResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/SomuItemService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/CreateSomuItemRequest.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/UpdateCaseDataValue.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/auditclient/AuditClient.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/SomuItemRepository.java, src/main/resources/db/migration/postgresql/V1_8__2274_RemoveSomuItemCaseSomuUuidUniqueConstraint.sql, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/SomuItemResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/SomuItemServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/dto/CreateSomuItemRequestTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/dto/UpdateCaseDataValueTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/client/auditclient/AuditClientTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/domain/repository/SomuItemRepositoryTest.java
Change to support multiple somu items per case and somu type.
=> HOCS-2274: Contribution fulfilment requirements

src/main/java/uk/gov/digital/ho/hocs/casework/domain/exception/RestResponseEntityExceptionHandler.java, src/test/java/uk/gov/digital/ho/hocs/casework/domain/exception/RestResponseEntityExceptionHandlerTest.java
* add event and stacktrace to uncaught exceptions log output
* write tests for error handler
=> HOCS-2301-"Unknown exception" exception only logs exception message

src/main/java/uk/gov/digital/ho/hocs/casework/application/LogEvent.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/exception/RestResponseEntityExceptionHandler.java, src/test/java/uk/gov/digital/ho/hocs/casework/domain/exception/RestResponseEntityExceptionHandlerTest.java
Adds missing details for HOCS-2301
* add stacktrace to error message
=> HOCS-2301-"Unknown exception" exception only logs exception message fix

src/main/resources/db/migration/postgresql/V1_11__2220-Add-MP-and-correspondents-details-to-dcu-workstack.sql
This change updates correspondents-by-json view to flag the primary correspondent
=> HOCS-2220-Flag correspondent to list of uuids in correspondents-by-json view

src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/SearchRequest.java
Additional search criteria for COMP: Address1, Email, Postcode.
Merge to epic.
=> HOCS-2838 : COMP search criteria

src/main/resources/db/migration/postgresql/V1_12__2847_COMP_PostcodeInSearchResults.sql
Add "postcode" to correspondents JSON view for use in COMP search results.
Merge to epic.
=> HOCS-2847 : COMP search results

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/ApplyExtensionRequest.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCaseSummaryResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/application/LogEvent.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/infoclient/InfoClient.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CaseData.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CaseDeadlineExtensionType.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CaseSummary.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/CaseDeadlineExtensionTypeRepository.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/MigrationCaseDataService.java, src/main/resources/db/migration/postgresql/V1_12__2583-Request-Pit-Extension.sql, src/test/java/uk/gov/digital/ho/hocs/casework/api/ApplyExtensionIntegrationTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCaseSummaryResponseTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/domain/exception/RestResponseEntityExceptionHandlerTest.java, src/test/resources/case/afterTest.sql, src/test/resources/case/beforeTest.sql
* Add endpoints to apply extensions to case
* Add db tables to hold extensions applied to case
=> Hocs 2583 request pit extension

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResource.java
=> Merge main into COMP epic.

src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java
When getting stages reduce the number of times stages are iterated over,
just iterate over stages once and perform actions.
=> HOCS-3423 Reduce number of times stages are iterated over

src/main/resources/application.properties
=> HOCS-3424 - Enable response compression.

src/main/resources/application.properties
=> HOCS-3424 - Enable response compression. (#404)

src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java
Temporary removal of somu data for workstack
=> HOCS-3566 - Don't return somu data for workstacks

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java
* Add CORRESPONDENT_UPDATED to TIMELINE_EVENTS
=> HOCS-3525 - Case Timeline not updated when correspondent updated

src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/StageTags.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/StageTagsDecorator.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/StageTagsDecoratorImpl.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetStageResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/Stage.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageTagsDecoratorImplTest.java
Adds tags field to stages, used on the frontend to indicate particular statuses about a case clearly on a workstack view.
=> HOCS-3311 Add tags onto stages in workstacks

src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java
Problem was caused by the updateContributions method not being called on the stage objects in the updateStages() method. I decided to not update updateStages() as this is called by the stage endpoint which famously should not have more data added to it.
=> HOCS-3774 adding contribution due date to data passed to mycases

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentService.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/AbstractCaseData.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/ActiveCaseViewData.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CaseData.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/ActiveCaseViewDataRepository.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/CaseDataRepository.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/MigrationCaseDataService.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataCreateCaseIntegrationTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataDeleteCaseIntegrationTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CorrespondentServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/AbstractCaseCopyStrategyTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyCompToComp2Test.java, src/test/java/uk/gov/digital/ho/hocs/casework/domain/repository/CaseDataRepositoryIntTest.java
Separate active_case and case_data entities to fix Case Extensions
=> Separate active_case and case_data entities

src/main/resources/db/migration/postgresql/V1_15__HotFix_RemoveSubselects.sql
Remove subselects from the query as they are causing performance issues
within production.
=> HOCS-3556: remove subselects

src/main/resources/db/migration/postgresql/V1_19__3892-Fix-active_case-stage-uuid.sql
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-3892
=> HOCS-3892 - Fix active_stage view to correct stage uuid

src/main/java/uk/gov/digital/ho/hocs/casework/client/auditclient/dto/AuditPayload.java
Added the missing organisation field from the extract for correspondents
=> HOCS-3936 add organisation to extract details

kube/kd/deployment.yaml, src/main/resources/application.properties
=> Hocs-3430 disable compression

src/main/java/uk/gov/digital/ho/hocs/casework/api/ActionDataDeadlineExtensionService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseActionsResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/ActionDataDeadlineExtensionInboundDto.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/auditclient/AuditClient.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/auditclient/dto/AuditPayload.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/ActionDataDeadlineExtension.java, src/main/resources/db/migration/postgresql/V1_38__4103_ADD_REASONS_COLUMN_TO_EXTENSIONS.sql, src/test/java/uk/gov/digital/ho/hocs/casework/api/ActionDataDeadlineExtensionServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseActionServiceIntegrationTest.java
HOCS-4103 PIT Extensions
* Allow multiple extensions
* Fix case notes for extensions
=> HOCS-4103 PIT Extensions

src/main/java/uk/gov/digital/ho/hocs/casework/api/ActionDataDeadlineExtensionService.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/ActionDataDeadlineExtensionServiceTest.java
Added an extra column to the foi workstack : 'Extended' shows if a case has been extended or not.
=> HOCS-4311 add extension indicator to foi workstack

src/main/java/uk/gov/digital/ho/hocs/casework/api/StageService.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/StageTagsDecorator.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/StageTagsDecoratorImpl.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/StageWithCaseData.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/StageServiceTest.java
Correctly set returned tags onto stages to return to the frontend
=> HOCS-4418 Fix tag decoration on stage service

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseActionsResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/dto/GetCaseSummaryResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/security/filters/GetCaseSummaryAuthFilterService.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseActionServiceIntegrationTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/security/filters/GetCaseSummaryAuthFilterServiceTest.java
Added case action data filtering.
=> HOCS-4596 add case action data filtering

src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/CaseDataRepository.java, src/main/resources/db/migration/postgresql/V1_40__4235_RECREATE_STAGE_DATA.sql
```
hocsprodapp=> explain analyze select * from stage_data_nm where team_uuid = 'd1ab8c4a-e131-4678-b141-d1f8a8951756';
QUERY PLAN                                                                                  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Nested Loop Left Join  (cost=1140.25..275980.04 rows=9427 width=1303) (actual time=2.167..219.607 rows=9925 loops=1)
->  Nested Loop Left Join  (cost=1122.67..110026.29 rows=9427 width=1272) (actual time=2.135..189.972 rows=9925 loops=1)
->  Gather  (cost=1114.08..28813.61 rows=9427 width=1256) (actual time=2.087..7.511 rows=9925 loops=1)
Workers Planned: 2
Workers Launched: 2
->  Nested Loop Left Join …
```
=> HOCS-4712: Change to the StageData view to help the Mpam teams

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentService.java, src/main/java/uk/gov/digital/ho/hocs/casework/client/documentclient/DocumentClient.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/ActionDataDeadlineExtensionRepository.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDocumentServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/client/documentclient/DocumentClientTest.java
JIRA Link : Remove actionDataUuid from Docs service
=> HOCS-5251 : Remove actionDataUuid from Docs service

src/main/resources/config/summary/POGR2.json
Add missing POGR2 `TelephoneResponseDateOfCall` and `TelephoneResponse`
summary fields.
=> HOCS-5551: add missing summary fields

src/main/resources/config/details/stages/TO.json, src/main/resources/config/summary/TO.json
Add the 'Other enquiry reason' to the TO summary and accordion configuration.
=> HOCS-5519: add field to 'TO' summary and accordion

src/main/resources/config/details/stages/BF.json, src/main/resources/config/details/stages/BF2.json, src/main/resources/config/details/stages/COMP.json, src/main/resources/config/details/stages/COMP2.json, src/main/resources/config/details/stages/DTEN.json, src/main/resources/config/details/stages/FOI.json, src/main/resources/config/details/stages/IEDET.json, src/main/resources/config/details/stages/MIN.json, src/main/resources/config/details/stages/MPAM.json, src/main/resources/config/details/stages/MTS.json, src/main/resources/config/details/stages/POGR.json, src/main/resources/config/details/stages/POGR2.json, src/main/resources/config/details/stages/SMC.json, src/main/resources/config/details/stages/TO.json, src/main/resources/config/details/stages/TRO.json
There are currently issues with the way the initial configuration was pulled that resulted in missing sections or total misconfiguration. This change corrects this and sets the configuration to the expected.
=> HOCS-5681: reconfigure accordion

src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/client/auditclient/MigrationAuditClient.java, src/main/resources/application-local.properties, src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseDataServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/migration/client/auditclient/MigrationAuditClientTest.java
Create the closed case migration audit events.
=> HOCS-5585: Migration audit

src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBfToBf2.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyCompToComp2.java, src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyPOGRtoPOGR2.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBfToBf2Test.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyCompToComp2Test.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyPOGRToPOGR2Test.java
HOCS-5833 resolve NPE when copying correspondent between stage 1 and 2 cases
=> HOCS-5833 resolve NPE when copying cases

src/main/resources/config/details/stages/IEDET.json
HOCS-5854 -
Currently as part of HOCS-5648 - display changes 
updated for summary page whereas for accordion 
this was missed. This PR will help to update both
summary and accordion text label in sync.
=> HOCS-5854 - Accordion display changes

src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyCompToComp2.java
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-5694
=> [HOCS-5694] Remove copying gender from COMP -> COMP2

src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyCompToComp2.java, src/main/resources/config/details/stages/COMP2.json, src/main/resources/config/summary/COMP2.json
Add the `CaseCreateContinue` configuration for summary and unallocated
accordion view.
Add the `XOriginatedFrom` for escalation cases to support workflow
process movement.
=> HOCS-5948: support comp stage2 creation

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseTagService.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/CaseTagRepository.java, src/main/resources/config/details/stages/IEDET.json, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataTagIntegrationTest.java
HOCS-5566- Build changes to include validation if 
the tag already exist for a case and respective 
junit test been corrected.
=> Hocs 5566 rejected by psu tag

src/main/resources/config/details/stages/COMP2.json
HOCS-6153 - Correct Complaint spelling on COMP2 accordion page.
=> HOCS-6153- correct Complaint speeling in COMP stage2 phase

src/main/resources/config/details/stages/TO.json
HOCS-6163 - This PR would help to fix show Business 
Unit Type for BF cases.
=> HOCS-6163- build changes to display Business unit type for BF cases

src/main/resources/config/details/stages/COMP.json
HOCS-6201-This PR would help UI in sync
between casework and workflow for UKVI
COMP triage phase.
=> HOCS-6201-json changes to fix UI COMP bug

src/main/resources/config/details/stages/IEDET.json, src/main/resources/config/summary/IEDET.json
This PR changes would include UI improvements for record case response
screen.
=> HOCS-6189:UI improvements for record case response

src/main/resources/config/details/stages/IEDET.json, src/main/resources/config/summary/IEDET.json
HOCS-6189: This PR would like to help update Substantiated 
label to substantiated for IEDET case type.
=> HOCS-6189:Modify Partially substantiated label

src/main/resources/config/details/stages/COMP2.json, src/main/resources/config/summary/COMP2.json
HOCS-6270:This PR would help to fix label issues
for external contractor and further stage 2 texts
in Summary and Accordion.
=> HOCS-6270:bug fix for display

src/main/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBfToBf2.java, src/main/resources/config/details/stages/BF.json, src/main/resources/config/summary/BF.json, src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBfToBf2Test.java
HOCS-5886:This PR would help to update sentence cases
for some of the case data fields. Also business has requested 
to remove gender, DOB and Channel from BF case type. 
Also same to be removed when data gets copied over to 
BF2 cases.
=> HOCS-5886:Build changes to remove unwanted fields and modify sentences

src/main/resources/config/details/stages/COMP2.json, src/main/resources/config/summary/COMP2.json
HOCS-6270: This PR helps to correct sentence correction
for Summary and Accordion in COMP2 cases.
=> HOCS-6270: Sentence correction

src/main/resources/config/details/stages/COMP2.json
HOCS-6424:This PR would help to update External 
contract label to External contractor
=> HOCS-6424:Modify sentence for external contractor

src/main/resources/config/details/stages/MIN.json
HOCS-6199: This PR would help to display correct label 
in the accordion and extracts. Currently its displaying 
value instead of label which will not make any sense to
the user.
=> HOCS-6199-Fix for displaying correct label in accordion and extracts

src/main/resources/config/details/stages/COMP.json, src/main/resources/config/details/stages/COMP2.json
Include the stage changes required for HOCS-5824, HOCS-5836, and HOCS-5837.
=> HOCS-6548: update complaint category stage view

src/main/resources/config/details/groups/WCS.json
=> HOCS-6511: WCS add new brought forward reasons to unallocated accordion

src/main/resources/config/details/stages/COMP2.json
Add missing accordion fields that are present for other complaint types.
=> HOCS-6552: add fields to accordion

.drone.yml, helm/hocs-casework-reporting.yaml, src/main/java/uk/gov/digital/ho/hocs/casework/reports/api/ReportResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/reports/domain/mapping/ExemptionDatesAgeAdjustmentLookup.java, src/main/java/uk/gov/digital/ho/hocs/casework/reports/domain/mapping/OpenCasesDataMapper.java, src/main/java/uk/gov/digital/ho/hocs/casework/reports/domain/mapping/StageNameValueMapper.java, src/main/java/uk/gov/digital/ho/hocs/casework/reports/domain/mapping/TeamNameValueMapper.java, src/main/java/uk/gov/digital/ho/hocs/casework/reports/domain/mapping/UserNameValueMapper.java, src/main/java/uk/gov/digital/ho/hocs/casework/reports/factory/ReportFactory.java, src/main/java/uk/gov/digital/ho/hocs/casework/reports/reports/OpenCasesReport.java, src/test/java/uk/gov/digital/ho/hocs/casework/reports/api/ReportResourceIntegrationTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/reports/domain/mapping/OpenCasesDataMapperTest.java
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-6526
=> [HOCS-6526] Add copy of casework with reporting flag enabled

src/main/resources/config/details/stages/COMP.json, src/main/resources/config/details/stages/COMP2.json, src/main/resources/config/summary/COMP.json, src/main/resources/config/summary/COMP2.json
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-6588
Replaces https://github.com/UKHomeOffice/hocs-casework/pull/945
=> [HOCS-6588] Flatten value mapping for directorate

src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseDataService.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseService.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/dto/CreateMigrationCaseRequest.java, src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseDataServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseServiceTest.java
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-6149
=> [HOCS-6149] Handle migrated cases with existing deadline

src/main/java/uk/gov/digital/ho/hocs/casework/domain/repository/CaseDataRepository.java
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-6652
=> [HOCS-6652] Exclude deleted cases in duplicate reference check

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResource.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResourceTest.java
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-6767
=> [HOCS-6767] Add endpoint to delete case by reference

src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/dto/BatchUpdateCaseDataRequest.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/dto/BatchUpdateCaseDataResponse.java, src/main/java/uk/gov/digital/ho/hocs/casework/migration/api/exception/MigrationExceptions.java, src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseIntegrationTest.java
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-6764
=> [HOCS-6703] Add endpoint to process batches of case data updates.

src/main/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResource.java, src/main/java/uk/gov/digital/ho/hocs/casework/security/AuthorisationAspect.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/security/AuthorisationAspectTest.java
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-6768
=> [HOCS-6768]  Delete case by ref - update permissions

src/main/resources/config/details/stages/COMP2.json, src/main/resources/config/summary/COMP2.json
HOCS-6793: Add REP to external contractor options. Tested both
workflow which display these options, summary, accordion and extracts 
were generated to test this scenario.
=> HOCS-6793: Add REP to external contractor options

src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/AbstractCaseData.java, src/main/java/uk/gov/digital/ho/hocs/casework/domain/model/CaseData.java, src/main/resources/db/migration/postgresql/R__6225_active_case_view.sql, src/test/java/uk/gov/digital/ho/hocs/casework/api/ActionDataAppealsServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/ActionDataDeadlineExtensionServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/ActionDataExternalInterestServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/ActionDataSuspendServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataDetailsServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataResourceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/CaseDataServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/AbstractCaseCopyStrategyTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBFToCOMPTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBFToSMCTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyBfToBf2Test.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyCompToComp2Test.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/factory/strategies/CopyPOGRToPOGR2Test.java, src/test/java/uk/gov/digital/ho/hocs/casework/api/utils/CaseDeadlineHelpersTest.java, src/test/java/uk/gov/digital/ho/hocs/casework/migration/api/MigrationCaseServiceTest.java
HOCS-6741: build changes to remove completed column from db and pojo.
=> HOCS-6741: build changes to remove completed column from db and pojos

src/main/resources/config/details/stages/COMP.json, src/main/resources/config/details/stages/COMP2.json, src/main/resources/config/summary/COMP.json, src/main/resources/config/summary/COMP2.json
HOCS-6791:Build changes for adding new UKVI COMP/COMP2 directorate and
respective business areas. This PR will make casework with both
old and new UKVI COMP/COMP2 directorate & business areas.
=> Hocs 6791 update directorate bus area ukvi

src/main/resources/config/details/stages/COMP2.json
HOCS-6802:Add updated COMP2 directorates
=> HOCS-6802:Add updated COMP2 directorates

src/main/resources/config/details/stages/COMP2.json
[](https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-6823)
- Comp2.json edited to add 'Enquiry reason' field to UKVI stage 2, Minor misconduct, triage accordion stage.
=> Add 'enquiry reason' field to Comp2 minor misconduct accordion
